### ISSUE TITLE
BOX_FILTER usage vs POINT_CLOUD_RANGE

### ISSUE THREAD

**Issue by darrenjkt** [CVMI-Lab/ST3D#19]
Hi,

Thanks for your work and ongoing responses to issues. I appreciate the support that you provide for this repo. 

In your `da_kitti_dataset.yaml` cfg file, you specified the following:
```
 
DATASET: 'KittiDataset'
DATA_PATH: '../data/kitti'

POINT_CLOUD_RANGE: [-75.2, -75.2, -2, 75.2, 75.2, 4]

...


DATA_PROCESSOR:
    - NAME: mask_points_and_boxes_outside_range
      REMOVE_OUTSIDE_BOXES: True

    - NAME: shuffle_points
      SHUFFLE_ENABLED: {
        'train': True,
        'test': False
      }

    - NAME: transform_points_to_voxels
      VOXEL_SIZE: [0.1, 0.1, 0.15]
      MAX_POINTS_PER_VOXEL: 5
      MAX_NUMBER_OF_VOXELS: {
        'train': 80000,
        'test': 90000
      }

TEST:
    BOX_FILTER: {
        'USE_IMAGE_AREA_FILTER': True,
        'FOV_FILTER': True,
        'LIMIT_RANGE': [-75.2, -75.2, -2, 75.2, 75.2, 4]
    }
```

What's the difference between the POINT_CLOUD_RANGE at the top of the cfg file, and the BOX_FILTER at the bottom? Both the nuscenes and waymo da configs don't have this TEST-BOX_FILTER parameter. It seems to me like the `mask_points_and_boxes_outside_range` function in DATA_PROCESSOR will filter out all the boxes and points that are outside the POINT_CLOUD_RANGE indicated above. 

Looking at this [line](https://github.com/CVMI-Lab/ST3D/blob/18b2d1e4f18b1941910f6a996ef3c221d34c1a45/pcdet/datasets/kitti/kitti_dataset.py#L285) for the TEST.BOX_FILTER, it seems like the box is filtering based on FOV. However, aren't we already filtering based on FOV when we specify FOV_POINTS_ONLY in the model cfgs? For example [here](https://github.com/CVMI-Lab/ST3D/blob/18b2d1e4f18b1941910f6a996ef3c221d34c1a45/tools/cfgs/da-nuscenes-kitti_models/secondiou/secondiou_old_anchor.yaml#L13). 

What's the usage of the BOX_FILTER and its various parameters? And why is it only for the KITTI dataset?

**Comment by jihanyang** [comment]
Hello, good question. 
1. This BOX_FILTER filters predicted boxes in inference stage, while `mask_points_and_boxes_outside_range`  works on data prepare stage for ground truths. 
2. Since KITTI dataset only annotates fov objects while other datasets annotate ring view objects, this filter is only applyed on KITTI.
3. FOV_POINTS_ONLY can filter the points outside fov. However, since both source labeled data and pseudo labeled target data  have full ring view points, I am not sure whether testing model on only fov points  would cause some negative transfer. In this regard, this BOX_FILTER works when we set FOV_POINTS_ONLY to False in KITTI. Actually, we found that in some situations, set FOV_POINTS_ONLY to False could even result in better performance (It seems that the provided checkpoint of Waymo -> KITTI has this characteristic).

**Comment by darrenjkt** [comment]
Thanks for the detailed response. That makes a lot of sense. 

Following on from that - in my understanding, when we set mask_points_and_boxes_outside_range and REMOVE_OUTSIDE_BOXES=True, it'll automatically remove the gt_boxes that are outside of the specific POINT_CLOUD_RANGE. E.g. if I set max x = 20m, it'll only keep any ground truth annotations that are less than 20m. 

However, when I exported some kitti pcds from the __getitem__ function during evaluation, it was not the case. I show the exported pcds below. The pcd below is with fov=True and POINT_CLOUD_RANGE: [-20, -20, -2, 20, 20, 4]. You can see that the pointcloud was succesfully filtered however the ground truth boxes at around 60m are still present. 

![image](https://user-images.githubusercontent.com/39115809/132947652-252aa060-aa37-46b9-bd52-d1ed8672a386.png)

For reference, this is what the full fov pointcloud with POINT_CLOUD_RANGE: [-75.2 -75.2, -2, 75.2, 75.2, 4] looks like. 
![image](https://user-images.githubusercontent.com/39115809/132947726-8e1c2cd8-60f6-4537-b60c-88051b206362.png)

How do I specify the cfg settings for the kitti dataset in test/train such that it'll filter the ground truth annotation boxes to only keep those that are in the specified POINT_CLOUD_RANGE?

**Comment by jihanyang** [comment]
See following codes, the mask gts will not works during inference.
https://github.com/CVMI-Lab/ST3D/blob/7b3ad3a61a72a9fd4fe7ee92164160d80a49fd19/pcdet/datasets/processor/data_processor.py#L36

Since mask gts already solve situations during training, you just need to consider inference time.
In this regard, you should modify following two place:
1. Filter predictions outside range similar to our BOX_FILTER configs.
https://github.com/CVMI-Lab/ST3D/blob/7b3ad3a61a72a9fd4fe7ee92164160d80a49fd19/pcdet/datasets/kitti/kitti_dataset.py#L284
2. Filter gts outside range in following place.
https://github.com/CVMI-Lab/ST3D/blob/7b3ad3a61a72a9fd4fe7ee92164160d80a49fd19/pcdet/datasets/kitti/kitti_dataset.py#L341

You can also refer to here since I already implement this function in Lyft dataset.
https://github.com/CVMI-Lab/ST3D/blob/7b3ad3a61a72a9fd4fe7ee92164160d80a49fd19/pcdet/datasets/lyft/lyft_dataset.py#L192-L201

**Comment by darrenjkt** [comment]
Amazing. Thanks for your prompt response and for giving such helpful direction.
