### ISSUE TITLE
About random_object_scaling and normalize_object_size

### ISSUE THREAD

**Issue by weiyithu** [CVMI-Lab/ST3D#27]
When you use nuscenes as the target domain, I see you do not use random_object_scaling and normalize_object_size techniques. But for KITTI you use them and can you give an explanation? Thank you.

**Comment by jihanyang** [comment]
Since nus and waymo are both collected in the USA, adjusting object size have minor influence, which have been discussed in the experiment section. MEMORY_ENSEMBLE.ENABLED is very intuitive, control using memory ensemble or not. UPDATE_PSEUDO_LABEL_INTERVAL the update interval of pseudo label. Since we find that updating pseudo label cannot work when nus as target domain, we disable pseudo label updating as soon as memory ensemble.
