### ISSUE TITLE
some question about table in paper

### ISSUE THREAD

**Issue by AndyYuan96** [CVMI-Lab/ST3D#4]
Hi, Jihan, thanks for open source the paper, I just have some question about tables in paper.
why do experiment in Table S11,S12,S13? Those experiments are evaluated use IOU=0.5,but before in Table 2,3,4 , you already do those experiment but with IOU=0.7? What's more, In Table S11, why it has opposite result with Table 2, in Table S11, source only is better that ROS, but in Table 2, ros is better than source only.

Thanks for reply.

**Comment by AndyYuan96** [comment]
What's more, for Table 3, for line "ST(w/SN) + Triplet", how do you deal with pseudo boxes which state is ignored, just discard it?

**Comment by jihanyang** [comment]
> Hi, Jihan, thanks for open source the paper, I just have some question about tables in paper.
> why do experiment in Table S11,S12,S13? Those experiments are evaluated use IOU=0.5,but before in Table 2,3,4 , you already do those experiment but with IOU=0.7? What's more, In Table S11, why it has opposite result with Table 2, in Table S11, source only is better that ROS, but in Table 2, ros is better than source only.
> 
> Thanks for reply.

Hello, we provide results with IoU =0.5 just for providing more information of differenet baselines and components. As for the opposite reuslt with Table 2 and Table S11, I guess this is caused by the less prediction number of ROS and SN. Source Only predicts around 17 boxes per scene when inference, while SN and ROS predict only around 12 boxes per scene. And these results in lower recall with IoU =0.3 (0.984, 0.979, 0.964 for Source Only, ROS and SN separately). The AP with lower IoU threshold benefits from the number of predictions. In summary, Source Only with more prediction can find where the objects are (find their location), but fails to precise localize them. SN and ROS improve the ablitiy of detector to localize to those objects but with less predictions, they miss some boxes.

**Comment by jihanyang** [comment]
> What's more, for Table 3, for line "ST(w/SN) + Triplet", how do you deal with pseudo boxes which state is ignored, just discard it?

You can refer to the statement under the equation (4) in our paper. We discard  negative boxes while make ignored boxes do not contribute to any loss terms.

**Comment by AndyYuan96** [comment]
> > What's more, for Table 3, for line "ST(w/SN) + Triplet", how do you deal with pseudo boxes which state is ignored, just discard it?
> 
> You can refer to the statement under the equation (4) in our paper. We discard negative boxes while make ignored boxes do not contribute to any loss terms.

About ROS configuration，SCALE_UNIFORM_NOISE is [0.7, 0.95] in cfg file da_waymo_dataset.yaml , but in paper, [0.75, 1.1], so just use cfg file configuration?

**Comment by jihanyang** [comment]
Just use the configuration would be ok. The [0.75, 1.1] includes the range for other settings such as waymo -> nus, nus -> lyft. Whether the minimum value is 0.75 or 0.7 do not matter a lot.

**Comment by AndyYuan96** [comment]
> Just use the configuration would be ok. The [0.75, 1.1] includes the range for other settings such as waymo -> nus, nus -> lyft. Whether the minimum value is 0.75 or 0.7 do not matter a lot.

many thanks。
