### ISSUE TITLE
Several problems with setup.py

### ISSUE THREAD

**Issue by andrewcaunes** [CVMI-Lab/ST3D#44]
Hello,
Thank you very much for this amazing work !

I have been trying to make the code (python setup.py develop) work on my windows 10, then 11, and now ubuntu, but have encountered countless errors with every environments (I've tried many Python versions, many torch, many cuda toolkits..)

Could you please detail one env list (versions for each dependencies) that is sure to function for the master branch ?
Would you also by any chance have a dockerfile to make it work ?

Up to now my trials were :
- Create fresh environment (conda)
- Install python, torch, torchvision, cudatoolkit and/or run "pip install -r requirements.txt"
- install spconv by cloning it from OpenPCDet and running "python setup.py bdist_wheel
-  run "python setup.py develop"

This has always given many errors and I have never been able to have it work.
I have been able to run the code ("python setup.py develop" gave no error) on docker but not on any real machine.

Hope you have some time to answer me !

**Comment by jihanyang** [comment]
Hello,
I think you can follow these three steps to setup your environment:
1. Follow the dockerfile here to install suitable pytorch verison and **spconv1.2.1**
https://github.com/open-mmlab/OpenPCDet/tree/master/docker
2. Checkout to branch `st3d_v0.3` in this repo (master branch only support pytorch 1.1 and spconv1.0).
3. Run `python setup.py develop`.

This should work for CUDA 10.2 pytorch 1.5, spconv1.2.1. BTW, since spconv does not support windows, above steps should be done on Linux env.

**Comment by andrewcaunes** [comment]
Hey,

Thank you very much !
After many trials I quit attempting to make it work on windows and switched to linux, on which I was able to make the repo work pretty quickly.

I was even able to make it work for Google Colab so that's nice.

Thanks a lot, great work !
