### ISSUE TITLE
Question about ST3D applied on other dataset 

### ISSUE THREAD

**Issue by ged0606** [CVMI-Lab/ST3D#46]
Hi, thanks for you great work.

Is there any plan to apply ST3D on other dataset, such as ONCE? :)
This [project](https://github.com/PointsCoder/ONCE_Benchmark) alse uses ST3D, but does not achive good adaption result on nuscenes_to_once, maybe due to improper configuration.

Beside, I apply ST3D on adaption from DeepRoute dataset to ONCE dataset, the adaption AP3D result  decrease to 40 from source result 55.

Can you give some advice to improve result on ONCE dataset?

Look forward to your soon reply!

**Comment by jihanyang** [comment]
Hello,
We don't have plan to apply ST3D to other datasets offically, since there are too many new emerged datasets like once, pandaset, livox, etc. It's believed that ST3D sould at least obtain higher performance than source only with suitable configuration. A very simple way is to set `UPDATE_PSEUDO_LABEL_INTERVAL=1000` (don't update), and obversve the performance change along self-training process. If the performance still decrease, that must be some improper configurations. In my experience, you can try to change to positive_thresh, negative_thresh and the matching threshold for each category in `ANCHOR_GENERATOR_CONFIG`. Hope that will be helpful.

**Comment by ged0606** [comment]
Thanks for reply, I will try it
